---
- include: install/{{ ansible_os_family }}.yml
  tags: [contrail.bare_metal_agent.package, package]

- include_role: name=node tasks_from=copy_ssl_certs
  tags: [install, contrail.bare_metal_agent.install]
  vars:
    ssl_certs_dir: '/etc/contrail/ssl'

- include: provision/main.yml
  tags: [contrail.bare_metal_agent.provision, provision]
