---
- name: Wait till config api server answers
  uri:
    url: "{{ api_server_url }}"
    status_code: 200
  register: api_server_connect_status
  until: api_server_connect_status.status == 200
  retries: 180
  delay: 1

- name: Run contrail-compute-setup script, logs at /var/log/contrail/contrail_vrouter_provisioning.log

  shell: "contrail-compute-setup --cfgm_ip {{ config_ip }} \
          --keystone_ip {{ keystone_ip }} \
          --self_ip {{ my_compute_ip }} {{ multi_intf_config }} \
          --hypervisor {{ hypervisor }} \
          --keystone_auth_protocol {{ keystone_auth_protocol }} \
          --keystone_auth_port {{ keystone_admin_port }} \
          --keystone_admin_user {{ keystone_admin_user }} \
          --keystone_admin_password {{ keystone_admin_password }} \
          --keystone_admin_tenant_name {{ keystone_admin_tenant }} \
          --control-nodes '{{ controllers_with_space_delim }}' \
          --collectors '{{ collectors_with_space_delim }}'"

# Configure XMPP Auth enable status
- name: Configure vrouter agent conf file if xmpp is enabled
  ini_file: dest={{ vrouter_agent_conf }} section=DEFAULT option={{ item.key }} value={{ item.value }}  create=yes
  with_dict:
      xmpp_auth_enable: "{{ xmpp_auth_enable }}"
