---
- name: Setup XMPP cert dirs if XMPP auth is enabled
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ xmpp_certs_dir }}"
    - "{{ xmpp_certs_dir }}/certs"
    - "{{ xmpp_certs_dir }}/private"

- name: Copy cert files for XMPP onto targets
  copy: src={{ item.src}} dest={{ item.dest }}
  with_items:
    - { src: "/etc/contrail_smgr/puppet/ssl/{{ ansible_hostname }}.pem", dest: "{{ xmpp_certs_dir }}/certs/server.pem" }
    - { src: "/etc/contrail_smgr/puppet/ssl/{{ ansible_hostname }}-privkey.pem", dest: "{{ xmpp_certs_dir }}/private/server-privkey.pem" }
    - { src: "/etc/contrail_smgr/puppet/ssl/ca-cert.pem", dest: "{{ xmpp_certs_dir }}/certs/ca-cert.pem" }

- name: Configure vrouter agent conf file if xmpp is enabled
  ini_file: dest={{ vrouter_agent_conf }} section=DEFAULT option={{ item.key }} value={{ item.value }}  create=yes
  with_dict:
    xmpp_auth_enable: "{{ xmpp_auth_enable }}"
    xmpp_dns_auth_enable: "{{ xmpp_dns_auth_enable }}"
    xmpp_server_cert: "{{ xmpp_certs_dir }}/certs/server.pem"
    xmpp_server_key: "{{ xmpp_certs_dir }}/private/server-privkey.pem"
    xmpp_ca_cert: "{{ xmpp_certs_dir }}/certs/ca-cert.pem"
