---
# Install all required packages from the contrail-install-packages repo
#
- name: Add contrail apt repository
  apt_repository:
    repo: "deb {{ contrail_apt_repo }} ./"
    state: present
  register: apt_repo_added
  when: contrail_apt_repo is defined
  ignore_errors: yes

- name: Allow unauthenticated packages for contrail packages to work
  copy: content='APT::Get::AllowUnauthenticated "true";' dest=/etc/apt/apt.conf.d/99allowunauth

- name: Pin contrail apt repo "contrail" release to priority 999
  copy: src=apt-preferences.conf dest=/etc/apt/preferences.d/contrail_repo.pref

- name: Run apt-get update
  apt: update_cache=yes
  when: apt_repo_added.get('changed',false)
  ignore_errors: yes

# python-docker should ideally list python-ipaddr as a dependency and the other
# packages should automatically get installed. This is a workaround for this missed
# upstream package dependency listing in the python-docker upstream deb
# definition. Manually installing missed dependencies of python-docker
- name: "Install python-docker and associated dependencies in Debian"
  package: name={{ item }} state=latest
  with_items:
      - python-docker
      - python-ipaddress
      - python-urllib3
