---
contrail_compute_mode: bare_metal
cloud_orchestrator: openstack
vcenter_compute_mode: "bare_metal"
enable_openstack_compute: "{{ false if provision_type == 'ISSU' else true }}"
compute_not_on_esxi: true
enable_openstack_on_vc_compute: false
enable_lbaas: true
deployment_platform: docker
no_upstart: "{{ true if deployment_platform == 'docker' }}"
#Tor Agent defaults
tor_agent: {}
tor_agent_list: []
kernel_version_installed: ""
config_server_list_derived: []
