---
- name: Install contrail cni package
  package: name="{{ contrail_cni_package_name }}" state=present

- name: Make sure cni directories exist
  file: path="{{ item }}" state=directory recurse=true
  with_items:
    - /var/log/contrail/cni
    - /etc/cni/net.d
    - /opt/cni/bin

- name: Create contrail-cni-nested.conf
  template: src=contrail-cni-nested.conf.j2 dest=/etc/cni/net.d/10-contrail-cni-nested.conf

- name: Create softlink contrail cni binary to /opt/cni/bin
  file: src=/usr/bin/contrail-kube-cni  dest=/opt/cni/bin/contrail-kube-cni state=link
  when: cloud_orchestrator != 'mesos'
